apps/catalog/urls.py
from gettext import Catalog
from django.conf.urls import patterns, include, url, static

from catalog.models import AdFavorits
from catalog.views import AdView,  MyAdListView, DeleteAd, CatalogView, \
    CategoryView, CreateAd, AdSearchView, EditAd, AdStrip, AdFavorities, ActivateAd, DeactivateAd, \
    BuyContactPageView, HideAd, decline_ad


urlpatterns = patterns('',

    url(r'^$', CatalogView.as_view(), name='catalog'),
    # url(r'^category/(?P<slug>[A-Za-z0-9-_]+)/', 'catalog.views.category', name='category'),
    url(r'^category/(?P<slug>[A-Za-z0-9_-]+)/(?P<ad_type>\w+)?', CategoryView.as_view(), name='category'),
    url(r'^ad/(?P<pk>\d+)/', AdView.as_view(), name='ad_view'),
    url(r'^ad/decline/(?P<pk>\d+)/', decline_ad, name='decline_ad'),
    url(r'^my_ads/(?P<state>\w+)/', MyAdListView.as_view(), name='my_ad_list_view_state'),
    url(r'^my_ads/', MyAdListView.as_view(), name='my_ad_list_view'),
    url(r'^search/', AdSearchView.as_view(), name='search'),
    url(r'^deals/(?P<pk>\d+)/$', AdView.as_view(template_name='catalog/deals-list.html'), name='ad_deals'),
    url(r'^buy_contact/page/', BuyContactPageView.as_view(), name='buy_contact_page'),
    url(r'^buy_contact/', 'catalog.views.buy_contact', name='buy_contact'),

    url(r'^create/', CreateAd.as_view(), name='create_ad'),
    url(r'^edit_ad/(?P<pk>\d+)/', EditAd.as_view(), name='edit_ad'),
    url(r'^delete/(?P<pk>\d+)/', DeleteAd.as_view(), name='delete_ad'),
    url(r'^activate/(?P<pk>\d+)/', ActivateAd.as_view(), name='activate_ad'),
    url(r'^deactivate/(?P<pk>\d+)/', DeactivateAd.as_view(), name='deactivate_ad'),

    url(r'^asearch/', 'catalog.views.asearch', name='a_search'),
    url(r'^hide/', HideAd.as_view(), name='hide'),

    url(r'^load_params/(?P<category>[\w\d_]+)/', 'catalog.views.load_params', name='load_params'),
    url(r'^upload_images/', 'catalog.views.upload_images', name='upload_images'),
    url(r'^upload_delete/(\d+)/', 'catalog.views.delete_images', name='upload_delete'),
    url(r'^get_cities/', 'catalog.views.get_cities', name='get_cities'),
    url(r'^check_city_ad_display/', 'catalog.views.check_city_ad_display', name='check_city_ad_display'),

    url(r'^strip/(?P<ad_type>\w+)?$', AdStrip.as_view(), name='strip'),
    url(r'^favorits/$', AdFavorities.as_view(), name='favorits'),
    url(r'^favorits/(add|del)/(\d+)/', 'catalog.views.AdFavoritiesChange', name='ad_favorits_change'),

)

apps/feedbacks/urls.py
from django.conf.urls import patterns, url
from feedbacks.views import FeedbackListView, CreateFeedback


urlpatterns = patterns('',
    url(r'^$', FeedbackListView.as_view(), name='feedbacks_all'),
    url(r'^(?P<pk>\d+)/', FeedbackListView.as_view(), name='feedbacks'),
    url(r'^create/$', CreateFeedback.as_view(), name='create_feedback'),
)

apps/payments/urls.py
from django.conf.urls import patterns, include, url, static
from payments.views import Balance

urlpatterns = patterns('',
    url(r'^$', Balance.as_view(), name='balance'),
    url(r'^redirect_robokassa/$', 'payments.views.redirect_robokassa', name='redirect_robokassa'),
    url(r'^payment_message_inline/$', 'payments.views.payment_message_inline', name='payment_message_inline'),
    url(r'^result/$', 'robokassa.views.result_view', name='robokassa_result'),
    url(r'^success/$', 'robokassa.views.success_view', name='robokassa_success'),
    url(r'^fail/$', 'robokassa.views.fail_view', name='robokassa_fail_view'),
)

dory/urls.py
from django.conf.urls import patterns, include, url, static
import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^chaining/', include('smart_selects.urls')),

    url(r'^$', include('content.urls')),
    url(r'^catalog/', include('catalog.urls')),
    url(r'^client/', include('client.urls')),
    url(r'^accounts/', include('client.urls')),
    url(r'^offers/', include('offers.urls')),
    url(r'^payments/', include('payments.urls')),
    url(r'^msg/', include('msg.urls')),
    url(r'^feedback/', include('feedbacks.urls')),
    url(r'^(?P<template_name>[A-Za-z0-9-]+)/$', 'content.views.test', name='test'),
)

urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/catalog/models.py
#! -*-coding:utf-8 -*-
import datetime

from django.db import models
from django.db.models import Q
from django.db.models.query import QuerySet

from catalog.settings import AD_TYPES, SELL, BUY, RENT_YOU, RENT_ME
from dory.settings import DAYS_FOR_EXPIRE
from tinymce.models import HTMLField
from django_geoip.models import City, Region
from smart_selects.db_fields import ChainedForeignKey

class Category(models.Model):
    machine_id = models.SlugField(u'Машинное имя', max_length=50, default='Cat', unique=True)
    name = models.CharField(u'Наименование категории', max_length=125)
    parent = models.ForeignKey('Category', limit_choices_to={'parent__isnull': True}, related_name='children',
                               null=True, blank=True, verbose_name=u'Родительская категория')
    parameters = models.ManyToManyField('Parameter_group', null=True, blank=True, through='CategoryParameterGroup')
    is_active = models.BooleanField(u'Отображать на сайте', default=True)
    price = models.FloatField(u'Цена категории', default=0, help_text=u'Показывать контакты для объявления после оплаты посетителем конкретной суммы указанной в админке для категории объявления')

    index = models.SmallIntegerField(u'Порядковый номер', default=1)
    color_price = models.FloatField(u'Цена выделения обьявления', default=0, help_text=u'Цена выделения обьявления для категории')


    def __unicode__(self):
        if self.parent:
            return self.name
        return self.name

    class Meta:
        ordering = ['index', 'name']
        verbose_name = u'Категория объявления'
        verbose_name_plural = u'Категории объявлений'

    def get_all_children(self):
        ids = [self.pk]
        for child_cat in self.children.all():
            ids.append(child_cat.pk)
        return Ad.objects.filter(category__in=ids)


class Parameter(models.Model):
    name = models.CharField(u'Значение параметра', max_length=125)
    child_groups = models.ManyToManyField('Parameter_group', verbose_name=u'Потомственные группы параметров',
                                          through='ParameterParameterGroup')

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u'Значение параметра'
        verbose_name_plural = u'Значения параметров'


class Parameter_group(models.Model):
    TYPE = [(0, u'Группа параметров'), (1, u'Текстовое поле'), (2, u'Числовое поле'), (3, u'Галка')]

    name = models.CharField(u'Название группы параметров', max_length=125)
    parameter_type = models.IntegerField(u'Тип параметра', choices=TYPE)
    parameters = models.ManyToManyField(Parameter, verbose_name=u'Параметры', related_name='parent_group', null=True,
                                        help_text=u'Только для параметров типа "Группа параметров"', blank=True)

    def get_parameters(self):
        res = {'name': self.name,
               'type': self.parameter_type,
               'params': []}
        if res['type'] == 0:
            for param in self.parameters.all():
                print param

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u'Параметр'
        verbose_name_plural = u'Параметры'


class CategoryParameterGroup(models.Model):
    category = models.ForeignKey('Category')
    parameter_group = models.ForeignKey('Parameter_group', related_name='category_parameters')


class ParameterParameterGroup(models.Model):
    parameter = models.ForeignKey('Parameter')
    parameter_group = models.ForeignKey('Parameter_group', related_name='Parameter_parameters')


class AdFilterManager(models.Manager):
    def get_queryset(self):
        return self.model.QuerySet(self.model).filter(is_deleted=False)


class Ad(models.Model):
    client = models.ForeignKey('client.Client', verbose_name=u'Клиент', related_name='client_ads')
    type = models.CharField(u'Тип объявления', max_length=50, choices=AD_TYPES)
    category = models.ForeignKey('Category', verbose_name=u'Категория', limit_choices_to={'parent__isnull': False},
                                 related_name='category_ads', null=True, blank=True)
    region = models.ForeignKey(Region, verbose_name=u'Регион')
    city = ChainedForeignKey(City, verbose_name=u'Город', chained_field="region", chained_model_field="region", related_name='city_ads')
    title = models.CharField(u'Название', max_length=125)
    price = models.FloatField(u'Цена', blank=True, null=True)
    price_free = models.BooleanField(u"Бесплатно", default=False)
    price_agreement = models.BooleanField(u"Договорная", default=False)
    text = HTMLField(u'Текст объявления', blank=True, null=True)
    phone = models.CharField(u'Телефон', max_length=100, blank=True, null=True)
    date = models.DateTimeField(u'Дата подачи', auto_now_add=True, default=datetime.datetime.now())

    priority = models.PositiveIntegerField(u'Приоритет', default=1)

    days_for_expire = models.PositiveIntegerField(u'Дней активно', default=DAYS_FOR_EXPIRE)
    is_active = models.BooleanField(u'Активно', default=True)
    is_shown = models.BooleanField(u'Отображается в ленте', default=True)
    is_deleted = models.BooleanField(u'Удалено', default=False)
    views = models.IntegerField(u'Просмотров', default=0, editable=False)
    check_color_price = models.BooleanField(u'Выделено объявления', default=False)

    declines = models.ManyToManyField("self", verbose_name=u"Отклоненные предложения", blank=True, null=True)

    client_declines = models.ManyToManyField("client.Client",
                                             verbose_name=u"Отклонили предложение",
                                             blank=True, null=True)

    objects = AdFilterManager()

    def __unicode__(self):
        return self.title

    def get_type(self):
        for i in AD_TYPES:
            if i[0] == self.type:
                return i[1]

    def get_phone(self):
        return self.phone or self.client.client_phone_numbers.first()

    def get_parameter_values(self):
        return [param.parameter_value for param in self.ad_parameters.all()]

    def get_cost(self):
        # orders = self.ad_option_orders.filter(closed=False, paid=False).aggregate(Sum('cost'))
        # options = self.options.filter(paid=False).aggregate(Sum('cost'))
        #return orders['cost__sum'] or 0
        return 0

    def is_favorits(self):
        return AdFavorits.objects.filter(ad=self).count()>0

    def get_deals(self):
        d_type = None
        if self.type == SELL:
            d_type = BUY
        elif self.type == BUY:
            d_type = SELL
        elif self.type == RENT_YOU:
            d_type = RENT_ME
        elif self.type == RENT_ME:
            d_type = RENT_YOU
        declines = self.declines.values_list('pk', flat=True)
        deals = Ad.objects.exclude(Q(client=self.client) | Q(pk__in=declines)) \
                          .filter(category=self.category, type=d_type)
        return deals

    class Meta:
        verbose_name = u'Объявление'
        verbose_name_plural = u'Объявления'

    class QuerySet(QuerySet):
        def filter_by_type(self, type):
            return self.filter(type=type)

        def filter_by_price(self, gt=None, lt=None):
            qs = self
            if gt: qs = qs.filter(price__gte=gt)
            if lt: qs = qs.filter(price__lte=lt)
            return qs


class AdPhone(models.Model):
    ad = models.ForeignKey(Ad, verbose_name=u'Объявление', related_name='phones')
    phone = models.CharField(u'Номер телефона', max_length=100)

    def __unicode__(self):
        return self.phone

    class Meta:
        verbose_name = u'Номер телефона объявления'
        verbose_name_plural = u'Номера телефонов объявления'


class AdPhoto(models.Model):
    img = models.ImageField(u'Изображение', upload_to='ad_photos', blank=True, null=True)
    ad = models.ForeignKey(Ad, related_name='ad_photos', null=True, blank=True)
    index = models.PositiveSmallIntegerField(u'Порядковый номер', default=0, null=True, blank=True)

    def __unicode__(self):
        return str(self.img.url)

    class Meta:
        ordering = ['index', 'id']


class AdTerms(models.Model):
    ad = models.ForeignKey(Ad, related_name='ad_terms', null=True, blank=True)
    term_text = models.CharField(u'Условия', max_length=255, blank=True)

    def __unicode__(self):
        return self.text


class AdParams(models.Model):
    ad = models.ForeignKey('Ad', verbose_name=u'Товар', related_name='ad_parameters')
    parameter = models.ForeignKey(Parameter_group, verbose_name=u'Тип параметра', null=True)
    parameter_value = models.ForeignKey(Parameter, verbose_name=u'Значение параметра',
                                        help_text=u'Только для параметров типа "Группа параметров"', null=True, blank=True)
    text = models.TextField(u'Значение текстового параметра',
                            help_text=u'Только для параметров типа "Текстовый параметр"', blank=True, null=True)
    number = models.FloatField(u'Значение числового параметра',
                               help_text=u'Только для параметров типа "Числовой параметр"', blank=True, null=True)
    boolean = models.BooleanField(u'Значение булевого параметра', help_text=u'Только для параметров типа "Галочка"',
                                  default=False)

    def __unicode__(self):
        return str(self.id)

    class Meta:
        verbose_name = u'Параметр объявления'
        verbose_name_plural = u'Параметры объявления'


class AdFavorits(models.Model):
    ad = models.ForeignKey(Ad, verbose_name=u'Избранное')
    client = models.ForeignKey('client.Client', verbose_name=u'Клиент', related_name='client_favorits')

    class Meta:
        verbose_name = u'Избранное объявление'
        verbose_name_plural = u'Избранные объявления'

apps/catalog/forms.py
#!-*-coding:utf-8-*-
from django import forms
from django.core.exceptions import ValidationError
from django.forms.widgets import TextInput

from catalog.models import Ad, AdPhoto, AdTerms
from django_geoip.models import IpRange, City, Region
from tinymce.widgets import TinyMCE


class NumberInput(TextInput):
    input_type = 'number'


class AdForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(AdForm, self).__init__(*args, **kwargs)
        self.fields['region'].queryset = Region.objects.order_by('name')

        if kwargs['initial']['client'].region and kwargs['initial']['client'].city:
            region = kwargs['initial']['client'].region
            city = kwargs['initial']['client'].city
        else:
            try:
                geoip_record = IpRange.objects.by_ip(kwargs['initial']['ip'])
                region = geoip_record.region
                city = geoip_record.city
            except IpRange.DoesNotExist:
                region = Region.objects.get(pk=83)
                city = City.objects.get(pk=2097)

        self.fields['region'].initial = region
        self.fields['city'].initial = city

    class Meta:
        model = Ad
        exclude = ('days_for_expire', 'priority', 'is_active', 'is_deleted', 'category',)
        widgets = {
            'client': forms.HiddenInput(),
            'title': forms.TextInput(attrs={'class': 'i-input input'}),
            'price': forms.TextInput(attrs={'class': 'i-input input input--short'}),
            'text': TinyMCE(attrs={'class': 'i-textarea textarea'}),
            'phone': forms.TextInput(attrs={'class': 'i-input input'}),
            'options': forms.CheckboxSelectMultiple(),
        }


class AdImageForm(forms.ModelForm):

    class Meta:
        model = AdPhoto
        widgets = {
            'ad': forms.HiddenInput(attrs={'class': 'good_for_image'}),
            'img': forms.FileInput(attrs={'class': 'upload-input', 'accept': 'image/*', 'multiple': 'true'}),
            'index': forms.HiddenInput()
        }


class AdTermsForm(forms.ModelForm):
    class Meta:
        model = AdTerms
        widgets = {
            'ad': forms.HiddenInput()
        }
        exclude = ['category',]

dory/templates/ad_offers.html
{% extends 'inner_base.html' %}

{% block head %}
	{% include 'blocks/b-main-head--auth.html' %}
{% endblock %}


{% block body %}
    <div class="page">
        {% include 'blocks/b-offer-list.html' %}
	</div>
{% endblock %}


{% block foot %}
	{% include 'blocks/b-main-foot.html' %}
{% endblock %}

dory/templates/add_good.html
{% extends 'inner_base.html' %} {% block body %}
    <div class="page page--margin">

    {% if is_good_added %}
        <h1>Объявление добавлено успешно</h1>
    {% else %}
        <h1>Разместить объявление</h1>
    {% endif %}

    <div class="b-ad-new">
    <div class="row">
    <div class="col">
    <div class="i-white-box">
    {% if is_good_added %}
        <div class="content">

            Вы можете посмотреть его по <a href="">ссылке</a>
        </div>
    {% else %}
        <form action="{% url 'add_good' %}" class="f-form" enctype="multipart/form-data" method="post">{% csrf_token %}
        {{ form.client }}
        <div class="content">
        <table class="for-form">
        <tr>
            <td>

            </td>
            <td>
                <label class="type-form">
                    <img src="http://placehold.it/32x32" alt="" class="ico">
                    <input type="radio" class="radio switch-form" name="form-type" data-show="form1" checked="checked">Объявление
                </label>

                <label class="type-form type-form--on">
                    <img src="http://placehold.it/32x32" alt="" class="ico">
                    <input type="radio" class="radio switch-form" name="form-type" data-show="form2">Акция
                </label>
            </td>
        </tr>
        <tr class="form1">
            <td>
                <div class="caption">Тип</div>
            </td>
            <td>
                <div class="field">
                    {{ form.kind.errors }}
                    {{ form.kind }}
                </div>
            </td>
        </tr>
        <tr class="form1">
            <td>
                <div class="caption">Город или населеный пункт</div>
            </td>
            <td>
                <div class="field">
                    {{ form.city.errors }}
                    {{ form.city }}
                </div>
            </td>
        </tr>

        <tr class="form1 before_params">
            <td>
                <div class="caption">Категория</div>
            </td>
            <td>
                <div class="field">
                    {{ category_errors }}
                    <select name="category" id="" title="weqweq">
                        <option data-val="qwe" value=""><strong>Выберите категорию</strong></option>
                        {% for category in categories %}
                            <option disabled data-val="qwe" value="{{ category.id }}">{{ category.name }}</option>
                            {% for subcategory in category.children.all %}
                                <option url_load_params="{% url 'load_params' category=subcategory.machine_id %}"
                                        data-val="qwe" value="{{ subcategory.id }}">
                                    &nbsp;&nbsp;{{ subcategory.name }}</option>
                            {% endfor %}
                        {% endfor %}
                    </select>
                </div>
            </td>
        </tr>
        <tr class="form1">
            <td>
                <div class="caption">Название</div>
            </td>
            <td>
                <div class="field">
                    {{ form.name.errors }}
                    {{ form.name }}
                </div>
            </td>
        </tr>
        <tr class="form1">
            <td>
                <div class="caption">Цена</div>
            </td>
            <td>
                <div class="field">
                    {{ form.price.errors }}
                    {{ form.price }}&nbsp;&nbsp;руб.
                </div>
            </td>
        </tr>
        <tr class="form1">
            <td>
                <div class="caption">Фото</div>
            </td>
            <td>
                <div class="field">
                    <div class="b-upload">
                        <div class="rezult"></div>
                        <div class="progress">
                            <div class="bar"></div>
                        </div>
                        <label>
                            {{ image_form.good }}
                            {{ image_form.img }}
                            {#                                                    <input type="file" class="upload-input" multiple accept="image/*">#}
                            <span class="add-link i-link i-link--fake">Добавить фото</span>
                        </label>
                    </div>
                </div>
            </td>
        </tr>
        <tr class="form1">
            <td>
                <div class="caption">Краткое описание</div>
            </td>
            <td>
                <div class="field">
                    {{ form.short_text.errors }}
                    {{ form.short_text }}
                </div>
            </td>
        </tr>
        <tr class="form1">
            <td>
                <div class="caption">Подробно</div>
            </td>
            <td>
                <div class="field">
                    {{ form.text.errors }}
                    {{ form.text }}
                </div>
            </td>
        </tr>
        <tr class="form1">
            <td>
                <div class="caption">Телефон</div>
            </td>
            <td>
                <div class="field">
                    {{ form.phone.errors }}
                    {{ form.phone }}
                </div>
            </td>
        </tr>


        <tr class="form2">
            <td>
                <div class="caption">Название</div>
            </td>
            <td>
                <div class="field">
                    <input type="text" name="" class="input i-input">
                </div>
            </td>
        </tr>
        <tr class="form2">
            <td>
                <div class="caption">Категория</div>
            </td>
            <td>
                <div class="field">
                    <select name="promo-ad" id="" title="weqweq">
                        <option data-val="qwe" value="1">Туризм</option>
                        <option data-val="qwe" value="2">Развлечения</option>
                        <option data-val="qwe" value="3">Обучение</option>
                    </select>
                </div>
            </td>
        </tr>
        <tr class="form2">
            <td>
                <div class="caption">Фото</div>
            </td>
            <td>
                <div class="field">
                    <div class="b-upload">

                        <div class="rezult"></div>
                        <div class="progress"></div>
                        <label>
                            <input type="file" class="upload-input" multiple accept="image/*">
                            <span class="add-link i-link i-link--fake">Добавить фото</span>
                        </label>

                    </div>
                </div>
            </td>
        </tr>
        <tr class="form2">
            <td>
                <div class="caption">Размер скидки</div>
            </td>
            <td>
                <div class="field">
                    <input type="text" name="" class="input i-input">
                </div>
            </td>
        </tr>
        <tr class="form2">
            <td>
                <div class="caption">Срок проведения акции</div>
            </td>
            <td>
                <div class="field">
                    <input type="text" name="" class="input i-input input--date" placeholder="с">&nbsp;—&nbsp;
                    <input type="text" name="" class="input i-input input--date" placeholder="по">
                </div>
            </td>
        </tr>
        <tr class="form2">
            <td>
                <div class="caption">Описание</div>
            </td>
            <td>
                <div class="field">
                    <textarea name="about-ad" rows="4" class="i-textarea textarea"></textarea>
                </div>
            </td>
        </tr>
        </table>
        </div>
        <footer class="footer">
            <div class="final-bt">
                <input type="submit" class=" i-bt" value="Разместить объявление">
            </div>
        </footer>
        </form>

        </div>
        </div>


        <div class="col ">
            <div class="i-white-box form1">
                <div class="b-item-ad i-white-box b-item-ad--one">
                    <header class="header">
                        <h3 class="title">
                            <a href="" class="i-link">
                                <span class="js-temp-type-ad">Продаю</span>
                                <span class="js-temp-name-ad">SEAT Altea</span>
                            </a>,
                            <span class="js-temp-price-ad">1 180 000</span>&nbsp;руб.</h3>
                    </header>
                    <div class="gallery js-photos-fullscreen">
                        <img src="http://placehold.it/300x201" alt="" height="180" width="240"
                             data-url="http://placehold.it/1025x768">
                    </div>
                    <div class="content js-temp-about-ad">
                        Это базовое объявление с одной картинкой. Добавить класс b-item-ad--one
                        <br>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo dolore delectus inventore
                        dolorum
                        aperiam tempora, animi explicabo placeat nostrum eveniet cumque a enim voluptatibus! Officiis
                        impedit magnam omnis ducimus in.
                    </div>
                    <footer class="footer">
                        <table>
                            <tr>
                                <td>
                                    <span class="action">
                                    <span class="i-link i-link--fake ad__action--offer">Отправить предложение</span>
                                    </span>
                                    <span class="action"> <a href="" class="i-link">Не интересует</a>
                                    </span>
                                    <span class="action"><a href="" class="i-link">Продвигать</a>
                                    </span>
{#                                    <span class="action"> <a href="" class="i-link">Отслеживать</a>#}
{#                                    </span>#}
                                                                </td>
                                                                <td>
                                    <span class="action"><a href="" class="i-link">Константинопольский
                                        константин</a>
                                    </span>
                                </td>
                                <td>14 янв 2013</td>
                            </tr>
                        </table>
                    </footer>
                </div>
            </div>

            <div class="form2">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed consequuntur libero tempora aliquam
                accusantium, a sint beatae dolorem provident, dignissimos veniam. Totam adipisci, accusamus nisi porro
                id
                assumenda sed delectus.
            </div>
        </div>

    {% endif %}

    </div>

    </div>
    </div>
{% endblock %}

dory/templates/auth.html
{% extends 'inner_base.html' %}
{% load client_tags %}
{% block body %}
<div class="page page--margin">
    <div class="bg--green-yellow auth-popup-box b-auth">
        <div class="auth__log-in">
            {% render_login_form %}
        </div>

        <div class="auth__sign-in">
            {% render_signup_form %}
        </div>
        <div class="auth__info error">
        </div>
    </div>
</div>
{% endblock %}

dory/templates/catalog.html
{% extends 'inner_base.html' %} {% block body %}
<div class="page page--margin">
    <div class="page-content b-catalog">
        {% for cat in categories %}
        <div class="list-wrap">
            <h3 class="title">
                <a href="{% url 'category' slug=cat.machine_id %}" class="title-link">{{ cat.name }}</a>
            </h3>
            <ul class="list">
                {% for subcat in cat.children.all %}
                <li class="item-wrap">
                    <a href="{% url 'category' slug=subcat.machine_id %}" class="item i-link">{{ subcat.name }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

dory/templates/category.html
{% extends 'inner_base.html' %} {% block head %} {% include 'blocks/b-main-head--auth.html' %} {% endblock %}
{% load thumbnail %}

{% block body %}
    <div class="page page--margin">

        <div class="page-content">
            <div class="ads">
                <div class="b-crumbs">
                    <span class="i-link i-link--fake category-popup-show-link">Категория:</span>
                    <br>

                    <h1 class="path">{{ category.parent.name }} → {{ category.name }}</h1>
                </div>
                {% if not category.parent %}
                    {% for cat in category.children.all %}
                        {% for good in cat.category_goods.all %}
                            {% if good in ad_list %}
                                {% include 'blocks/b-category-ad.html' %}
                            {% endif %}
                        {% endfor %}
                    {% endfor %}
                {% else %}
                    {% for good in category.category_goods.all %}
                        {% if good in ad_list %}
                            {% include 'blocks/b-category-ad.html' %}
                        {% endif %}
                    {% endfor %}
                {% endif %}

            </div>
        </div>
        <div class="page-side stickyeah">
            <div class="page-side-w">
                {% include 'blocks/b-side.html' %}
            </div>
        </div>
    </div>
{% endblock %} {% block foot %} {% include 'blocks/b-main-foot.html' %} {% endblock %}

dory/templates/my_ad_list_view.html
{% extends 'inner_base.html' %}
{% block head %}
    {% include 'blocks/b-main-head--auth.html' %}
{% endblock %}
{% block body %}
    {% for ad in ads %}
        {% include 'blocks/b-ad--my-ad.html' %}
    {% empty %}
        <br>
        <h3>Список объявлений пуст</h3>
    {% endfor %}
{% endblock %}
{% block foot %}
    {% include 'blocks/b-main-foot.html' %}
{% endblock %}